### ISSUE TITLE
Pinterest example

### ISSUE THREAD

**Issue by taglia3** [Touchwonders/Transition#1]
Hi,
where can I find the demo project with the _pinterest_ transition?
In the readme there is the gif, but I didn't found it in the example directory.

**Comment by roberthein** [comment]
Hi Matteo,
Good question! We discovered a bug in this example and are busy fixing this. We will add it to the rest of the examples and update this issue when it's fixed. 🚀

**Comment by taglia3** [comment]
Hi Robert,
have you fixed the issue related to the 'pinterest' example?

**Comment by roberthein** [comment]
Sorry for the delay, we are looking into it and hope to update you this week!

**Comment by betteray** [comment]
Hi,
and i wanna know is it must requred to be ios 10+ . can you support more ios version? tks .

**Comment by toineheuvelmans** [comment]
@OXOOFF: Transition makes use of iOS 10's [UIViewPropertyAnimator](https://developer.apple.com/reference/uikit/uiviewpropertyanimator), so that makes for quite a definitive answer: yes, only iOS 10+.

@taglia3 @roberthein will reply to your pending request a.s.a.p.

**Comment by roberthein** [comment]
@taglia3 You can find the pinterest-like-example in a separate branch:
https://github.com/Touchwonders/Transition/tree/feature/pinterest-like-example

**Comment by toineheuvelmans** [comment]
I have made several improvements to the framework in general and to the NavigationTransitionsExample specifically. It has been merged into `master` now, available in release 1.1.0.
