### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by netspencer** [Touchwonders/Transition#11]
This project uses many methods deprecated in Swift 4.2. Right now, it is possible to build it with Swift 4.0 and include it in a project build with Swift 4.2. However, it would be nice to have an update to the project itself to work with Swift 4.2.

**Comment by netspencer** [comment]
alright well i’ll close this issue now due to inactivity. will probably make a PR in the future

**Comment by toineheuvelmans** [comment]
Hi @netspencer, I'm very sorry you didn't hear from us, I must admit it got snowed under a bit 😔. I have just published release 1.2.1, which includes PR #9 from @kdvmgn, and I've updated the examples projects accordingly.

**Comment by netspencer** [comment]
thanks for your comment. totally understand
