### ISSUE TITLE
Provided examples contain bugs/glitches

### ISSUE THREAD

**Issue by dkarbayev** [Touchwonders/Transition#6]
When I start interactive unwinding and cancel it by releasing my finger before threshold is passed, transition becomes broken. Please see following video explanations: https://www.dropbox.com/s/v6vb2gczopew1sw/Transition.mov

**Comment by toineheuvelmans** [comment]
Hi @dkarbayev, thank you for submitting this, I really appreciate that you made the video which clearly demonstrates some issues.
We are currently a bit low on resources to address these right on (as goes for the other open issues 😬), but I will do my best to get time for it on our planning a.s.a.p.

**Comment by p3scobar** [comment]
**/Pods/Transition/Transition/Classes/AnimationLayer.swift:37:42: Static var 'full' is internal and cannot be referenced from a default argument value**

    public init(range: AnimationRange = .full, timingParameters: AnimationTimingParameters, animation: @escaping AnimationFunction) {
        self.range = range
        self.timingParameters = timingParameters
        self.animation = animation
    }


// Any idea how to fix this??? Thanks in advance.

**Comment by toineheuvelmans** [comment]
@dkarbayev 
I have addressed the built-in transition animations, which incorrectly removed the visible view when the transition was cancelled.
	The glitches (jumps) that are particularly apparent in the ModaltransitionsExample oddly enough seem to be specific to iOS 11 – I first tried to reproduce on iOS 10 but without luck. The issue occurs when a UIViewPropertyAnimator is reversed and continued. Apparently this is an unaddressed regression since iOS 11: https://openradar.appspot.com/34674968
	I have created a temporary "fix" that continues the animation by specifying a linear timing curve, instead of none (when none are specified, the originial timing parameters should be used). This seems to avoid the jumping in the animation.
	See more here: https://stackoverflow.com/questions/46406670/uiviewpropertyanimator-different-behaviour-on-ios10-and-ios11-reversing-an-anima

**Comment by toineheuvelmans** [comment]
@p3scobar 
I have adjusted the access level of that property, as well as some others. Please create a separate issue in the future such that related comments and actions stay organized.
